/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as propertySharesSol from './PropertyShares.sol/index.js';
export * as transferGateSol from './TransferGate.sol/index.js';
export { KYCRegistry__factory } from './KYCRegistry__factory.js';
export { PropertyFactory__factory } from './PropertyFactory__factory.js';