/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITransferGate } from './ITransferGate.js';
export type { PropertyShares } from './PropertyShares.js';