services:
  database:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - neoimmo_db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - NeoImmo-docker

  server:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - NeoImmo-docker
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  neoimmo_db_data:

networks:
  NeoImmo-docker:
    driver: bridge