/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKYCRegistry__factory } from './IKYCRegistry__factory.js';
export { TransferGate__factory } from './TransferGate__factory.js';