/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'KYCRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KYCRegistry__factory>
getContractFactory(name: 'PropertyFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PropertyFactory__factory>
getContractFactory(name: 'ITransferGate', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITransferGate__factory>
getContractFactory(name: 'PropertyShares', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PropertyShares__factory>
getContractFactory(name: 'IKYCRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKYCRegistry__factory>
getContractFactory(name: 'TransferGate', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TransferGate__factory>

  getContractAt(name: 'KYCRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KYCRegistry>
getContractAt(name: 'PropertyFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PropertyFactory>
getContractAt(name: 'ITransferGate', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITransferGate>
getContractAt(name: 'PropertyShares', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PropertyShares>
getContractAt(name: 'IKYCRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKYCRegistry>
getContractAt(name: 'TransferGate', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TransferGate>

  deployContract(name: 'KYCRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KYCRegistry>
deployContract(name: 'PropertyFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyFactory>
deployContract(name: 'ITransferGate', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITransferGate>
deployContract(name: 'PropertyShares', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyShares>
deployContract(name: 'IKYCRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKYCRegistry>
deployContract(name: 'TransferGate', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TransferGate>

  deployContract(name: 'KYCRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KYCRegistry>
deployContract(name: 'PropertyFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyFactory>
deployContract(name: 'ITransferGate', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITransferGate>
deployContract(name: 'PropertyShares', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyShares>
deployContract(name: 'IKYCRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKYCRegistry>
deployContract(name: 'TransferGate', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TransferGate>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  