/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as propertySharesSol from './PropertyShares.sol/index.js';
export type { propertySharesSol };
import type * as transferGateSol from './TransferGate.sol/index.js';
export type { transferGateSol };
export type { KYCRegistry } from './KYCRegistry.js';
export type { PropertyFactory } from './PropertyFactory.js';
export * as factories from './factories/index.js';
export { KYCRegistry__factory } from './factories/KYCRegistry__factory.js';
export { PropertyFactory__factory } from './factories/PropertyFactory__factory.js';
export type { ITransferGate } from './PropertyShares.sol/ITransferGate.js';
export { ITransferGate__factory } from './factories/PropertyShares.sol/ITransferGate__factory.js';
export type { PropertyShares } from './PropertyShares.sol/PropertyShares.js';
export { PropertyShares__factory } from './factories/PropertyShares.sol/PropertyShares__factory.js';
export type { IKYCRegistry } from './TransferGate.sol/IKYCRegistry.js';
export { IKYCRegistry__factory } from './factories/TransferGate.sol/IKYCRegistry__factory.js';
export type { TransferGate } from './TransferGate.sol/TransferGate.js';
export { TransferGate__factory } from './factories/TransferGate.sol/TransferGate__factory.js';