/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PropertyFactory {
      
    export type PropertyInfoStruct = {token: AddressLike, gate: AddressLike, admin: AddressLike, name: string, symbol: string, metadataURI: string, metadataHash: BytesLike, createdAt: BigNumberish}

    export type PropertyInfoStructOutput = [token: string, gate: string, admin: string, name: string, symbol: string, metadataURI: string, metadataHash: string, createdAt: bigint] & {token: string, gate: string, admin: string, name: string, symbol: string, metadataURI: string, metadataHash: string, createdAt: bigint }
  
    }

  export interface PropertyFactoryInterface extends Interface {
    getFunction(nameOrSignature: "createProperty" | "gate" | "owner" | "propertyAt" | "propertyCount" | "propertyInfo" | "renounceOwnership" | "setGate" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "GateUpdated" | "OwnershipTransferred" | "PropertyCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createProperty', values: [string, string, string, BytesLike]): string;
encodeFunctionData(functionFragment: 'gate', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'propertyAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'propertyCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'propertyInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setGate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'createProperty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setGate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace GateUpdatedEvent {
      export type InputTuple = [gate: AddressLike];
      export type OutputTuple = [gate: string];
      export interface OutputObject {gate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PropertyCreatedEvent {
      export type InputTuple = [token: AddressLike, admin: AddressLike, gate: AddressLike, name: string, symbol: string, metadataURI: string, metadataHash: BytesLike];
      export type OutputTuple = [token: string, admin: string, gate: string, name: string, symbol: string, metadataURI: string, metadataHash: string];
      export interface OutputObject {token: string, admin: string, gate: string, name: string, symbol: string, metadataURI: string, metadataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PropertyFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): PropertyFactory;
    waitForDeployment(): Promise<this>;

    interface: PropertyFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createProperty: TypedContractMethod<
      [name_: string, symbol_: string, metadataURI: string, metadataHash: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    gate: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    propertyAt: TypedContractMethod<
      [index: BigNumberish, ],
      [PropertyFactory.PropertyInfoStructOutput],
      'view'
    >
    

    
    propertyCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    propertyInfo: TypedContractMethod<
      [token: AddressLike, ],
      [PropertyFactory.PropertyInfoStructOutput],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setGate: TypedContractMethod<
      [newGate: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createProperty'): TypedContractMethod<
      [name_: string, symbol_: string, metadataURI: string, metadataHash: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'gate'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'propertyAt'): TypedContractMethod<
      [index: BigNumberish, ],
      [PropertyFactory.PropertyInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'propertyCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'propertyInfo'): TypedContractMethod<
      [token: AddressLike, ],
      [PropertyFactory.PropertyInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setGate'): TypedContractMethod<
      [newGate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'GateUpdated'): TypedContractEvent<GateUpdatedEvent.InputTuple, GateUpdatedEvent.OutputTuple, GateUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PropertyCreated'): TypedContractEvent<PropertyCreatedEvent.InputTuple, PropertyCreatedEvent.OutputTuple, PropertyCreatedEvent.OutputObject>;

    filters: {
      
      'GateUpdated(address)': TypedContractEvent<GateUpdatedEvent.InputTuple, GateUpdatedEvent.OutputTuple, GateUpdatedEvent.OutputObject>;
      GateUpdated: TypedContractEvent<GateUpdatedEvent.InputTuple, GateUpdatedEvent.OutputTuple, GateUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PropertyCreated(address,address,address,string,string,string,bytes32)': TypedContractEvent<PropertyCreatedEvent.InputTuple, PropertyCreatedEvent.OutputTuple, PropertyCreatedEvent.OutputObject>;
      PropertyCreated: TypedContractEvent<PropertyCreatedEvent.InputTuple, PropertyCreatedEvent.OutputTuple, PropertyCreatedEvent.OutputObject>;
    
    };
  }