/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TransferGateInterface extends Interface {
    getFunction(nameOrSignature: "blockedCountries" | "blocklist" | "canTransfer" | "kyc" | "owner" | "setBlockedCountry" | "setBlocklist"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'blockedCountries', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'blocklist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'canTransfer', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'kyc', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'setBlockedCountry', values: [BytesLike, boolean]): string;
encodeFunctionData(functionFragment: 'setBlocklist', values: [AddressLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'blockedCountries', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'blocklist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBlockedCountry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBlocklist', data: BytesLike): Result;
  }

  

  export interface TransferGate extends BaseContract {
    
    connect(runner?: ContractRunner | null): TransferGate;
    waitForDeployment(): Promise<this>;

    interface: TransferGateInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    blockedCountries: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    blocklist: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    canTransfer: TypedContractMethod<
      [from: AddressLike, to: AddressLike, arg2: BigNumberish, ],
      [[boolean, string]],
      'view'
    >
    

    
    kyc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setBlockedCountry: TypedContractMethod<
      [cc: BytesLike, blocked: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setBlocklist: TypedContractMethod<
      [user: AddressLike, blocked: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'blockedCountries'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'blocklist'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'canTransfer'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, arg2: BigNumberish, ],
      [[boolean, string]],
      'view'
    >;
getFunction(nameOrSignature: 'kyc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setBlockedCountry'): TypedContractMethod<
      [cc: BytesLike, blocked: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBlocklist'): TypedContractMethod<
      [user: AddressLike, blocked: boolean, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }