/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITransferGate__factory } from './ITransferGate__factory.js';
export { PropertyShares__factory } from './PropertyShares__factory.js';