/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITransferGate, ITransferGateInterface } from "../../PropertyShares.sol/ITransferGate.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "canTransfer",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      },
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ITransferGate__factory {
    static readonly abi = _abi;
    static createInterface(): ITransferGateInterface {
      return new Interface(_abi) as ITransferGateInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITransferGate {
      return new Contract(address, _abi, runner) as unknown as ITransferGate;
    }
  }
  